CREATE OR ALTER TRIGGER BBCT.T_STICKER_HISTORY 
ON BBCT.T_STICKER
AFTER INSERT, DELETE,UPDATE
AS
BEGIN
	DECLARE @INSERTCOUNT int, @DELETEDCOUNT int, 
	@INSERTEDSTICKERNO varchar(13), @INSERTEDREMARK varchar(5), @INSERTEDREPLICATECOUNT varchar(10), @INSERTEDDATETAGGED varchar(10), @INSERTEDTAGGEDBY varchar(10), 
	@INSERTEDDATECREATED datetime2(6), @INSERTEDCREATEDBY varchar(10), @INSERTEDDATEDELIVERED date,
	@DELETEDSTICKERNO varchar(13), @DELETEDREMARK varchar(5), @DELETEDREPLICATECOUNT varchar(10), @DELETEDDATETAGGED varchar(10), @DELETEDTAGGEDBY varchar(10), 
	@DELETEDDATECREATED datetime2(6), @DELETEDCREATEDBY varchar(10), @DELETEDDATEDELIVERED date
	SET @INSERTCOUNT = (SELECT COUNT(*) FROM INSERTED);
	SET @DELETEDCOUNT = (SELECT COUNT(*) FROM DELETED);

	SET @INSERTEDSTICKERNO = (SELECT STICKER_NO FROM INSERTED);
	SET @INSERTEDREMARK = (SELECT ISNULL(REMARK, 'NULL') FROM INSERTED);
	SET @INSERTEDREPLICATECOUNT = (SELECT CONVERT(varchar(10), REPLICATE_COUNT) FROM INSERTED);
	SET @INSERTEDDATETAGGED = (SELECT CONVERT(varchar(10), DATE_TAGGED, 6) FROM INSERTED);
	SET @INSERTEDTAGGEDBY = (SELECT TAGGED_BY FROM INSERTED);
	SET @INSERTEDDATECREATED = (SELECT DATE_CREATED FROM INSERTED);
	SET @INSERTEDCREATEDBY = (SELECT CREATED_BY FROM INSERTED);
	SET @INSERTEDDATEDELIVERED = (SELECT DATE_DELIVERED FROM INSERTED);

	SET @DELETEDSTICKERNO = (SELECT STICKER_NO FROM DELETED);
	SET @DELETEDREMARK = (SELECT ISNULL(REMARK, 'NULL') FROM DELETED);
	SET @DELETEDREPLICATECOUNT = (SELECT CONVERT(varchar(10),REPLICATE_COUNT) FROM DELETED);
	SET @DELETEDDATETAGGED = (SELECT CONVERT(varchar(10), DATE_TAGGED, 6) FROM DELETED);
	SET @DELETEDTAGGEDBY = (SELECT TAGGED_BY FROM DELETED);
	SET @DELETEDDATECREATED = (SELECT DATE_CREATED FROM DELETED);
	SET @DELETEDCREATEDBY = (SELECT CREATED_BY FROM DELETED);
	SET @DELETEDDATEDELIVERED = (SELECT DATE_DELIVERED FROM DELETED);

	SET NOCOUNT ON;
	
		if (@INSERTCOUNT >0 AND @DELETEDCOUNT > 0)
			BEGIN
				PRINT 'Update';
				if (@INSERTEDSTICKERNO  != @DELETEDSTICKERNO)
				BEGIN
					INSERT INTO BBCT.T_HISTORY (DATE_DONE, TABLE_NAME, ACTIVITY, DATA_FROM, DATA_TO, DESCRIPTION, USERNAME) 
					VALUES (CURRENT_TIMESTAMP, 'T_STICKER', 'U', @DELETEDSTICKERNO, @INSERTEDSTICKERNO , 'Updated ' + ' erc sticker number from ' + @DELETEDSTICKERNO + ' to ' + @INSERTEDSTICKERNO, 'CF000000');
				END
				if (@INSERTEDREMARK != @DELETEDREMARK)
				BEGIN
					INSERT INTO BBCT.T_HISTORY (DATE_DONE, TABLE_NAME, ACTIVITY, DATA_FROM, DATA_TO, DESCRIPTION, USERNAME) VALUES (CURRENT_TIMESTAMP, 'T_STICKER', 'U', @DELETEDREMARK, @INSERTEDREMARK, 'Updated ' +@INSERTEDSTICKERNO+ ' remark from ' + @DELETEDREMARK + ' to ' + @INSERTEDREMARK, 'CF000000');
				END
				if (@INSERTEDREPLICATECOUNT  != @DELETEDREPLICATECOUNT)
				BEGIN
					INSERT INTO BBCT.T_HISTORY (DATE_DONE, TABLE_NAME, ACTIVITY, DATA_FROM, DATA_TO, DESCRIPTION, USERNAME) VALUES (CURRENT_TIMESTAMP, 'T_STICKER', 'U', @DELETEDREPLICATECOUNT, @INSERTEDREPLICATECOUNT, 'Updated ' +@INSERTEDSTICKERNO+ ' replicate count from ' + @DELETEDREPLICATECOUNT + ' to ' + @INSERTEDREPLICATECOUNT, 'CF000000');
				END
				if (@INSERTEDDATETAGGED != @DELETEDDATETAGGED)
				BEGIN
					INSERT INTO BBCT.T_HISTORY (DATE_DONE, TABLE_NAME, ACTIVITY, DATA_FROM, DATA_TO, DESCRIPTION, USERNAME) VALUES (CURRENT_TIMESTAMP, 'T_STICKER', 'U', @DELETEDDATETAGGED, @INSERTEDDATETAGGED, 'Updated ' +@INSERTEDSTICKERNO+ ' date tagged from ' + @DELETEDDATETAGGED + ' to ' + @INSERTEDDATETAGGED, 'CF000000');
				END
				if (@INSERTEDTAGGEDBY != @DELETEDTAGGEDBY)
				BEGIN
					INSERT INTO BBCT.T_HISTORY (DATE_DONE, TABLE_NAME, ACTIVITY, DATA_FROM, DATA_TO, DESCRIPTION, USERNAME) VALUES (CURRENT_TIMESTAMP, 'T_STICKER', 'U', @DELETEDTAGGEDBY, @INSERTEDTAGGEDBY, 'Updated ' +@INSERTEDSTICKERNO+ ' tagged by from ' + @DELETEDTAGGEDBY + ' to ' + @INSERTEDTAGGEDBY, 'CF000000');
				END
			END
		else 
			if (@INSERTCOUNT >0 AND @DELETEDCOUNT=0)
				BEGIN
					INSERT INTO BBCT.T_HISTORY (DATE_DONE, TABLE_NAME, ACTIVITY, DATA_FROM, DATA_TO, DESCRIPTION, USERNAME) VALUES (CURRENT_TIMESTAMP, 'T_STICKER', 'I', null, @INSERTEDSTICKERNO, 'Inserted ' + @INSERTEDSTICKERNO, 'CF000000');		
				END
			else 
			if (@INSERTCOUNT=0 AND @DELETEDCOUNT > 0)
			BEGIN
				INSERT INTO BBCT.T_HISTORY (DATE_DONE, TABLE_NAME, ACTIVITY, DATA_FROM, DATA_TO, DESCRIPTION, USERNAME) VALUES (CURRENT_TIMESTAMP, 'T_STICKER', 'D', @DELETEDSTICKERNO, null, 'Deleted ' + @DELETEDSTICKERNO, 'CF000000');
			END
END
