CREATE OR ALTER TRIGGER BBCT.T_SEAL_STICKER_PAIR_HISTORY 
ON BBCT.T_SEAL_STICKER_PAIR
AFTER INSERT, DELETE,UPDATE
AS
BEGIN
	DECLARE @INSERTCOUNT int, @DELETEDCOUNT int, 
	@INSERTEDCOVERPAGENO varchar(13), @INSERTEDSTICKERNO varchar(11), @INSERTEDDATECREATED varchar(10),
	@INSERTEDCREATEDBY varchar(10), @INSERTEDDATEDELIVERED varchar(10), @INSERTEDMERALCOSEALNO varchar(13),  
	@DELETEDCOVERPAGENO varchar(13), @DELETEDSTICKERNO varchar(11), @DELETEDDATECREATED varchar(10),
	@DELETEDCREATEDBY varchar(10), @DELETEDDATEDELIVERED varchar(10), @DELETEDMERALCOSEALNO varchar(13)  
	
	SET @INSERTCOUNT = (SELECT COUNT(*) FROM INSERTED);
	SET @DELETEDCOUNT = (SELECT COUNT(*) FROM DELETED);

	SET @INSERTEDCOVERPAGENO = (SELECT COVER_PAGE_NO FROM INSERTED);
	SET @INSERTEDSTICKERNO = (SELECT STICKER_NO FROM INSERTED);
	SET @INSERTEDDATECREATED = (SELECT CONVERT(varchar(10), DATE_CREATED, 126) FROM INSERTED);
	SET @INSERTEDCREATEDBY = (SELECT CREATED_BY FROM INSERTED);
	SET @INSERTEDDATEDELIVERED = (SELECT CONVERT(varchar(10), DATE_DELIVERED, 6) FROM INSERTED);
	SET @INSERTEDMERALCOSEALNO = (SELECT MERALCO_SEAL_NO FROM INSERTED);
	
	SET @DELETEDCOVERPAGENO = (SELECT COVER_PAGE_NO FROM DELETED);
	SET @DELETEDSTICKERNO = (SELECT STICKER_NO FROM DELETED);
	SET @DELETEDDATECREATED = (SELECT CONVERT(varchar(10), DATE_CREATED, 126) FROM DELETED);
	SET @DELETEDCREATEDBY = (SELECT CREATED_BY FROM DELETED);
	SET @DELETEDDATEDELIVERED = (SELECT CONVERT(varchar(10), DATE_DELIVERED, 6) FROM DELETED);
	SET @DELETEDMERALCOSEALNO = (SELECT MERALCO_SEAL_NO FROM DELETED);

	SET NOCOUNT ON;
	
		if (@INSERTCOUNT >0 AND @DELETEDCOUNT > 0)
			BEGIN
				PRINT 'Update';
				if (@INSERTEDCOVERPAGENO  != @DELETEDCOVERPAGENO)
				BEGIN
					INSERT INTO BBCT.T_HISTORY (DATE_DONE, TABLE_NAME, ACTIVITY, DATA_FROM, DATA_TO, DESCRIPTION, USERNAME) VALUES (CURRENT_TIMESTAMP, 'T_SEAL_STICKER_PAIR', 'U', @DELETEDCOVERPAGENO, @INSERTEDCOVERPAGENO, 'Updated ' + @DELETEDCOVERPAGENO + ' and ' + @DELETEDSTICKERNO + ' seal-sticker pair cover seal number from ' + @DELETEDCOVERPAGENO + ' to ' + @INSERTEDCOVERPAGENO, 'A');
				END
				if (@INSERTEDSTICKERNO != @DELETEDSTICKERNO)
				BEGIN
					INSERT INTO BBCT.T_HISTORY (DATE_DONE, TABLE_NAME, ACTIVITY, DATA_FROM, DATA_TO, DESCRIPTION, USERNAME) VALUES (CURRENT_TIMESTAMP, 'T_SEAL_STICKER_PAIR', 'U',  @DELETEDSTICKERNO, @INSERTEDSTICKERNO, 'Updated ' + @DELETEDCOVERPAGENO + ' and ' + @DELETEDSTICKERNO + ' seal-sticker pair erc sticker number from ' + @DELETEDSTICKERNO + ' to ' + @INSERTEDSTICKERNO, 'A');
				END
				if (@INSERTEDDATECREATED  != @DELETEDDATECREATED)
				BEGIN
					INSERT INTO BBCT.T_HISTORY (DATE_DONE, TABLE_NAME, ACTIVITY, DATA_FROM, DATA_TO, DESCRIPTION, USERNAME) VALUES (CURRENT_TIMESTAMP, 'T_SEAL_STICKER_PAIR', 'U', @DELETEDDATECREATED, @INSERTEDDATECREATED, 'Updated ' + @INSERTEDCOVERPAGENO + ' and ' + @INSERTEDSTICKERNO + ' seal-sticker pair date created from ' + @DELETEDDATECREATED + ' to ' + @INSERTEDDATECREATED, 'A');
				END
				if (@INSERTEDCREATEDBY != @DELETEDCREATEDBY)
				BEGIN
					INSERT INTO BBCT.T_HISTORY (DATE_DONE, TABLE_NAME, ACTIVITY, DATA_FROM, DATA_TO, DESCRIPTION, USERNAME) VALUES (CURRENT_TIMESTAMP, 'T_SEAL_STICKER_PAIR', 'U',@DELETEDCREATEDBY, @INSERTEDCREATEDBY, 'Updated ' + @INSERTEDCOVERPAGENO + ' and ' + @INSERTEDSTICKERNO + ' seal-sticker pair created by from ' + @DELETEDCREATEDBY + ' to ' + @INSERTEDCREATEDBY, 'A');
				END
				if (@INSERTEDDATEDELIVERED != @DELETEDDATEDELIVERED)
				BEGIN
					INSERT INTO BBCT.T_HISTORY (DATE_DONE, TABLE_NAME, ACTIVITY, DATA_FROM, DATA_TO, DESCRIPTION, USERNAME) VALUES (CURRENT_TIMESTAMP, 'T_SEAL_STICKER_PAIR', 'U', @DELETEDDATEDELIVERED, @INSERTEDDATEDELIVERED, 'Updated ' + @INSERTEDCOVERPAGENO + ' and ' + @INSERTEDSTICKERNO + ' seal-sticker pair date delivered from ' + @DELETEDDATEDELIVERED + ' to ' + @INSERTEDDATEDELIVERED, 'A');
				END
			END
		else 
			if (@INSERTCOUNT >0 AND @DELETEDCOUNT=0)
				BEGIN
					INSERT INTO BBCT.T_HISTORY (DATE_DONE, TABLE_NAME, ACTIVITY, DATA_FROM, DATA_TO, DESCRIPTION, USERNAME) VALUES (CURRENT_TIMESTAMP, 'T_SEAL_STICKER_PAIR', 'I', null, @INSERTEDCOVERPAGENO+ ', ' + @INSERTEDSTICKERNO, 'Inserted ' + @INSERTEDCOVERPAGENO+ ' and ' + @INSERTEDSTICKERNO + ' seal-sticker pair', 'A');		
				END
			else 
			if (@INSERTCOUNT=0 AND @DELETEDCOUNT > 0)
			BEGIN
				INSERT INTO BBCT.T_HISTORY (DATE_DONE, TABLE_NAME, ACTIVITY, DATA_FROM, DATA_TO, DESCRIPTION, USERNAME) VALUES (CURRENT_TIMESTAMP, 'T_SEAL_STICKER_PAIR', 'D', @DELETEDCOVERPAGENO + ', ' + @DELETEDSTICKERNO, null, 'Deleted ' + @DELETEDCOVERPAGENO + ' and ' + @DELETEDSTICKERNO + ' seal-sticker pair', 'A');
			END
END
